server:
  port: 8443
  ssl:
    key-store: file://.keystore/taco-cloud.jks
    key-store-password: <key-store-password>
    key-password: <key-password>
spring:
  profiles:
    active:
      - local
    schema:
      - order-schema.sql
      - ingredient-schema.sql
      - taco-schema.sql
      - user-schema.sql
    data:
      - ingredients.sql
logging:
  path: /var/logs/
  file: TacoCloud.log
  level:
    root: DEBUG
    org.springframework.security: DEBUG
greeting:
  welcome: You are using ${spring.application.name}
taco.orders.page-size: 10

---
spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword

logging:
  lvel:
    root: WARN
