server:
  port: 8443
  ssl:
    key-store: file://~/.keystore/mykeys.jks
    key-store-password: <key-store-password>
    key-password: <key-password>
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taco_cloud
    username: your_username
    password: your_password
    driver-class-name: com.postgresql.jdbc.Driver
    jndi-name: java:/comp/env/jdbc/tacoCloudDS
    schema:
      - order-schema.sql
      - ingredient-schema.sql
      - taco-schema.sql
      - user-schema.sql
    data:
      - ingredients.sql
logging:
  path: /var/logs/
  file: TacoCloud.log
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG
