spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: YOUR CLIENT ID GOES HERE
            client-secret: YOUR CLIENT SECRET GOES HERE
          vk:
            client-id: YOUR CLIENT ID GOES HERE
            client-secret: YOUR CLIENT SECRET GOES HERE
            clientAuthenticationMethod: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: friends
        provider:
          vk:
            authorization-uri: https://oauth.vk.com/authorize?display=page&v=5.131
            token-uri: https://oauth.vk.com/access_token
            user-info-uri: https://api.vk.com/method/users.get?v=5.131
            user-name-attribute: id
